<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- special targets file for ExampleMod. Fits in place of the one in /Mod Sources -->  
  <Import Project="src/WorkspaceInfo.targets" />
  <PropertyGroup>
    <_InstalledTmlTargetsPath>$(tModLoaderSteamPath)\tMLMod.targets</_InstalledTmlTargetsPath>
    <_RepoTmlTargetsPath>$(MSBuildThisFileDirectory)src\tModLoader\Terraria\release_extras\tMLMod.targets</_RepoTmlTargetsPath>
    <_RepoTmlOutputPath>$(MSBuildThisFileDirectory)src\tModLoader\Terraria\bin\$(Configuration)\net10.0\</_RepoTmlOutputPath>
    <tModLoaderSteamPath Condition="!Exists('$(_InstalledTmlTargetsPath)')">$(_RepoTmlOutputPath)</tModLoaderSteamPath>
    <tMLSteamPath Condition="'$(tMLSteamPath)' == ''">$([MSBuild]::EnsureTrailingSlash('$(tModLoaderSteamPath)'))</tMLSteamPath>
  </PropertyGroup>
  <Import Project="$(tModLoaderSteamPath)/tMLMod.targets" Condition="Exists('$(tModLoaderSteamPath)/tMLMod.targets')" />
  <Import Project="$(_RepoTmlTargetsPath)" Condition="!Exists('$(tModLoaderSteamPath)/tMLMod.targets') AND Exists('$(_RepoTmlTargetsPath)')" />
  
  <ItemGroup>
    <!-- unfortunately VS Goto Defintion doesn't work on pdb source paths, only direct project references -->
    <Reference Remove="$(tMLSteamPath)**/FNA.dll"/>
    <Reference Remove="$(tMLSteamPath)**/ReLogic.dll"/>
    <Reference Remove="$(tMLSteamPath)**/tModLoader.dll"/>
    <ProjectReference Include="$(MSBuildThisFileDirectory)FNA/FNA.Core.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/tModLoader/ReLogic/ReLogic.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/tModLoader/Terraria/Terraria.csproj" />
  </ItemGroup>
</Project>
